# Java Gradle CircleCI 2.0 configuration file
version: 2
jobs:
    build:
        branches:
        only:
            - main
            - develop
        docker:
            - image: maciejmalecki/c64libci:0.1.8

        working_directory: ~/repo

        environment:
            JVM_OPTS: -Xms256m -Xmx768m
            TERM: dumb

        steps:
            - checkout
            - run: ./gradlew licenseAsm build
            - run: ./gradlew licenseAsm build-crt
